"""
marketplace/sdk/docgen.py
--------------------------
Generates a Markdown documentation file for a Bazaar marketplace skill.

Reads manifest.yaml and Python docstrings.  Renders docs/skills/<name>.md
using a Jinja2 template.

Usage (programmatic):
    from marketplace.sdk.docgen import generate_doc
    doc_path = generate_doc(Path("marketplace/skills/weather_fetcher"))
    print(doc_path)          # docs/skills/weather_fetcher.md

Usage (CLI):
    python -m marketplace.sdk.cli skill doc weather_fetcher
"""

from __future__ import annotations

import importlib
import inspect
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger("bazaar.sdk")

# ---------------------------------------------------------------------------
# Jinja2 template (inline — avoids a separate file dependency)
# ---------------------------------------------------------------------------

_DOC_TEMPLATE = """\
# {{ manifest.name }}

> Bazaar marketplace skill · v{{ manifest.version }} · by {{ manifest.author }}

## Description

{{ manifest.description }}

## Category

`{{ manifest.category }}`

## Permissions required

{% if manifest.permissions %}
| Permission | Why |
|---|---|
{% for p in manifest.permissions %}| `{{ p }}` | *Declared in manifest* |
{% endfor %}
{% else %}
None — this skill requires no special permissions.
{% endif %}

## Skill dependencies

{% if manifest.skill_dependencies %}
{% for dep in manifest.skill_dependencies %}- `{{ dep }}`
{% endfor %}
{% else %}
None.
{% endif %}

## Tools

{% for tool in manifest.tools %}
### `{{ tool.name }}`

{{ tool.description }}

**Module:** `{{ tool.module }}`  
**Function:** `{{ tool.function }}`

{% if tool_docstrings.get(tool.name) %}
```
{{ tool_docstrings[tool.name] }}
```
{% endif %}

{% if tool.parameters %}
#### Parameters

| Name | Type | Description |
|---|---|---|
{% for param_name, param in tool.parameters.items() %}| `{{ param_name }}` | `{{ param.get("type", "any") }}` | {{ param.get("description", "") }} |
{% endfor %}
{% endif %}
{% endfor %}

## Installation

```bash
arcturus skill install {{ manifest.name }}
```

## Intent triggers

{% for trigger in manifest.intent_triggers %}- `{{ trigger }}`
{% endfor %}

---

*Generated by `arcturus skill doc` — Arcturus Bazaar SDK*
"""


# ---------------------------------------------------------------------------
# Doc generator
# ---------------------------------------------------------------------------

def _extract_docstring(module_path: str, function: str) -> str:
    """
    Import *module_path* and return the docstring of *function*.

    Returns an empty string if the module or function cannot be imported.
    """
    try:
        mod = importlib.import_module(module_path)
        fn = getattr(mod, function, None)
        if fn is None:
            return ""
        doc = inspect.getdoc(fn) or ""
        return doc
    except Exception as exc:
        logger.debug("Could not extract docstring from %s.%s: %s",
                     module_path, function, exc)
        return ""


def generate_doc(
    skill_dir: Path,
    out_root: Optional[Path] = None,
) -> Path:
    """
    Generate a Markdown doc file for the skill at *skill_dir*.

    Args:
        skill_dir: Root directory of the skill (must contain manifest.yaml).
        out_root:  Root directory for output files.
                   Default: ``docs/skills/`` relative to CWD.

    Returns:
        Path to the generated .md file.

    Raises:
        FileNotFoundError: If manifest.yaml does not exist.
        ValueError: If the manifest cannot be loaded.
    """
    from marketplace.skill_base import load_manifest
    from jinja2 import Environment

    manifest_path = skill_dir / "manifest.yaml"
    if not manifest_path.exists():
        raise FileNotFoundError(f"manifest.yaml not found: {manifest_path}")

    manifest = load_manifest(manifest_path)

    # Extract docstrings for each declared tool
    tool_docstrings: dict[str, str] = {}
    for tool in manifest.tools:
        tool_docstrings[tool.name] = _extract_docstring(tool.module, tool.function)

    # Render Markdown
    env = Environment(keep_trailing_newline=True)
    tpl = env.from_string(_DOC_TEMPLATE)
    content = tpl.render(manifest=manifest, tool_docstrings=tool_docstrings)

    # Write output
    out_root = out_root or Path("docs") / "skills"
    out_root.mkdir(parents=True, exist_ok=True)
    out_path = out_root / f"{manifest.name}.md"
    out_path.write_text(content, encoding="utf-8")

    logger.info("Doc written to %s", out_path)
    return out_path
