"""Tests for Integrity: Checksum generation, verification, and tamper detection."""
import pytest
from pathlib import Path
from marketplace.integrity import compute_checksum, verify_checksum, stamp_manifest


# --- Helpers ---

def create_skill(base_path: Path, name: str = "test_skill") -> Path:
    """Create a minimal skill directory."""
    skill_dir = base_path / name
    tools_dir = skill_dir / "tools"
    tools_dir.mkdir(parents=True, exist_ok=True)
    
    (skill_dir / "manifest.yaml").write_text(f"""
name: {name}
version: 1.0.0
description: A test skill
checksum: ""
""")
    
    (tools_dir / "hello.py").write_text('def greet():\n    return "Hello!"')
    return skill_dir


# --- Checksum Computation Tests ---

def test_compute_checksum_returns_sha256_format(tmp_path):
    """Checksum should start with 'sha256:' followed by 64 hex chars."""
    skill_dir = create_skill(tmp_path)
    checksum = compute_checksum(skill_dir)
    assert checksum.startswith("sha256:")
    assert len(checksum) == 71  # "sha256:" (7) + 64 hex chars


def test_compute_checksum_is_deterministic(tmp_path):
    """Same directory should always produce the same checksum."""
    skill_dir = create_skill(tmp_path)
    checksum_1 = compute_checksum(skill_dir)
    checksum_2 = compute_checksum(skill_dir)
    assert checksum_1 == checksum_2


def test_compute_checksum_changes_when_file_modified(tmp_path):
    """Modifying any file should change the checksum."""
    skill_dir = create_skill(tmp_path)
    original = compute_checksum(skill_dir)
    
    # Modify a tool file
    (skill_dir / "tools" / "hello.py").write_text('def greet():\n    return "Hacked!"')
    
    modified = compute_checksum(skill_dir)
    assert original != modified


def test_compute_checksum_changes_when_file_added(tmp_path):
    """Adding a new file should change the checksum."""
    skill_dir = create_skill(tmp_path)
    original = compute_checksum(skill_dir)
    
    (skill_dir / "tools" / "backdoor.py").write_text("import os; os.system('evil')")
    
    modified = compute_checksum(skill_dir)
    assert original != modified


def test_compute_checksum_changes_when_file_renamed(tmp_path):
    """Renaming a file should change the checksum (path is hashed too)."""
    skill_dir = create_skill(tmp_path)
    original = compute_checksum(skill_dir)
    
    # Rename hello.py → goodbye.py
    (skill_dir / "tools" / "hello.py").rename(skill_dir / "tools" / "goodbye.py")
    
    renamed = compute_checksum(skill_dir)
    assert original != renamed


def test_compute_checksum_ignores_pycache(tmp_path):
    """__pycache__ directories should NOT affect the checksum."""
    skill_dir = create_skill(tmp_path)
    original = compute_checksum(skill_dir)
    
    # Add __pycache__ files (generated by Python, not authored)
    cache_dir = skill_dir / "__pycache__"
    cache_dir.mkdir()
    (cache_dir / "hello.cpython-311.pyc").write_bytes(b"bytecode")
    
    with_cache = compute_checksum(skill_dir)
    assert original == with_cache


def test_compute_checksum_raises_for_missing_dir(tmp_path):
    """compute_checksum should raise FileNotFoundError for non-existent dirs."""
    with pytest.raises(FileNotFoundError):
        compute_checksum(tmp_path / "nonexistent")


# --- Stamp Tests ---

def test_stamp_manifest_writes_checksum(tmp_path):
    """stamp_manifest should write the checksum into the manifest file."""
    skill_dir = create_skill(tmp_path)
    checksum = stamp_manifest(skill_dir)
    
    import yaml
    with open(skill_dir / "manifest.yaml") as f:
        data = yaml.safe_load(f)
    
    assert data["checksum"] == checksum
    assert checksum.startswith("sha256:")


def test_stamp_then_verify_passes(tmp_path):
    """A freshly stamped skill should pass verification."""
    skill_dir = create_skill(tmp_path)
    stamp_manifest(skill_dir)
    assert verify_checksum(skill_dir) is True


# --- Verification Tests ---

def test_verify_passes_for_unsigned_skill(tmp_path):
    """A skill with no checksum (unsigned) should pass verification."""
    skill_dir = create_skill(tmp_path)
    assert verify_checksum(skill_dir) is True


def test_verify_fails_for_tampered_skill(tmp_path):
    """A stamped skill with modified files should FAIL verification."""
    skill_dir = create_skill(tmp_path)
    stamp_manifest(skill_dir)
    
    # Tamper with a file AFTER stamping
    (skill_dir / "tools" / "hello.py").write_text("import os; os.system('steal_data')")
    
    assert verify_checksum(skill_dir) is False


def test_verify_fails_for_added_file(tmp_path):
    """Adding a new file after stamping should FAIL verification."""
    skill_dir = create_skill(tmp_path)
    stamp_manifest(skill_dir)
    
    # Add a backdoor file
    (skill_dir / "tools" / "backdoor.py").write_text("evil()")
    
    assert verify_checksum(skill_dir) is False


def test_verify_fails_for_wrong_checksum(tmp_path):
    """A manifest with a manually edited checksum should FAIL."""
    skill_dir = create_skill(tmp_path)
    
    import yaml
    manifest_path = skill_dir / "manifest.yaml"
    with open(manifest_path) as f:
        data = yaml.safe_load(f)
    data["checksum"] = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
    with open(manifest_path, "w") as f:
        yaml.dump(data, f)
    
    assert verify_checksum(skill_dir) is False